### ISSUE TITLE
TypeError: _imagemin2.default is not a constructor

### ISSUE THREAD

**Issue by beekman** [1000ch/atom-imagemin#1]
When right-clicking on images in the sidebar and choosing "Minify Image" on my Mac running El Capitan:
TypeError: _imagemin2.default is not a constructor
    at minify (/Users/djbeeker/.atom/packages/imagemin/index.js:72:20)
    at atom-workspace.<anonymous> (/Users/djbeeker/.atom/packages/imagemin/index.js:44:64)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1110:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:342:25)
    at emitThree (events.js:110:13)
    at EventEmitter.emit (events.js:188:7)

**Comment by 1000ch** [comment]
@beekman Sorry for delay, fixed in the newest version 🙏
